title = "Foward"

#第一祖，支持多组配置，每组配置必须是最多一个server，最少一个inner
[[server]]
group = "给跳板机取个组名"
addr  = "跳板机的地址，如 122.122.122.122:22"
user  = "跳板机的用户帐号"
auth  = "认证信息，可以是密码、密钥文件、密钥文本"
[[inner]]
group = "所属跳板机的组名"
addr  = "远程机器的ip，如 192.168.1.53:22"
bind  = "绑定到本地机器的端口，如 :60053"
[[inner]]
group = "所属跳板机的组名"
addr  = "远程机器的ip，如 192.168.1.54:22"
bind  = "绑定到本地机器的端口，如 :60054"
